### ISSUE TITLE
Opening a modal from a slash command

### ISSUE THREAD

**Issue by Fraysa** [soxtoby/SlackNet#100]
It seems you can't return a modal from a slash command (`ISlashCommanderHandler` implementation) as it expects a return of `ISlashCommandResponse` while `ISlackApiClient.Views.Open` returns a `ViewResponse`.

Any way around this?

**Comment by soxtoby** [comment]
Slack lets you respond to a slash command directly with a message, which is what `SlashCommandResponse` is for. If you're opening a modal instead of sending back a message, you can simply return `null` for the response. The `ISlackApiClient.Views.Open` call will open the modal, not the response to the slash command.

Hope that helps.

**Comment by Fraysa** [comment]
@soxtoby 3 questions:

1. Will returning `null` suffice for the acknowledgment so Slack won't complain?
2. `ISlackApiClient.Views.Open` requires a trigger ID, I assume this is the same ID that gets sent through the `SlashCommand` argument when handling the slash command?
3. Can an action within a model open another modal with an action?

**Comment by soxtoby** [comment]
1. Yes.
2. Correct.
3. Yes. Use `ISlackApiClient.Views.Push` instead of `Open` to open a nested modal. You can have [up to 3 modals](https://api.slack.com/surfaces/modals/using#pushing_views) on the stack.
