### ISSUE TITLE
UNAUTHENTICATED: cache_error

### ISSUE THREAD

**Issue by hughesmk** [soxtoby/SlackNet#107]
Something recently changed on the slack side of things which is causing us to get exceptions in socketmode typically between the first and second socket connecting.  The message received is UNAUTHENTICATED: cache_error and is throws a JsonReaderException as the message payload is not a JSON response.

At the time of the message the client reports that it is connected, but clearly something is slightly off.  I am sure that the root of this is on the slack side as we have an older bot that only started getting this error 2 weeks ago, but hoping that there is a better way of handling this error in SlackNet.   Currently we end up logging out and back in repeatedly until we are successful in getting connected without the cache_error which is sub-optimal.

**Comment by soxtoby** [comment]
I haven't been able to find anything about this online unfortunately, so I guess we'll just have try to handle it and see what happens. I'll start by logging and skipping any messages that can't be deserialized, and see if that works. If it turns out the connection is broken at that point, then I guess we'll have to handle that message explicitly.

In case we _do_ need to handle that precise message, can you confirm that it's literally `"UNAUTHENTICATED: cache_error"`?

**Comment by soxtoby** [comment]
Messages that can't be deserialized are now ignored in [v0.10.8](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.8) - give that a go and let me know if it does the job.

**Comment by hughesmk** [comment]
6/23/2022 9:28:58 AM - XML - [WebSocketFactory.onsocketmessagereceived] WS Msg Received: UNAUTHENTICATED: cache_error


The update most certainly stops the crashes which is a huge improvement.  Thanks!
