### ISSUE TITLE
How could I read the result of a menu box?

### ISSUE THREAD

**Issue by Anti-Apple4life** [soxtoby/SlackNet#112]
Current code: https://pastebin.com/Zuk2N5gB

**Comment by soxtoby** [comment]
Hi @Anti-Apple4life, you can refer to the `LegacyColorSelector` [registration](https://github.com/soxtoby/SlackNet/blob/master/SlackNet.EventsExample/Startup.cs#L34) and [handler](https://github.com/soxtoby/SlackNet/blob/master/SlackNet.EventsExample/ColorSelector.cs#L14) in the EventsExample project to see an example of handling menu selections. Note that you'll need to set up a public web server and configure your Slack app to send interaction requests there.

I'd highly recommend upgrading your Slack app and using [socket mode](https://api.slack.com/apis/connections/socket) with [blocks](https://api.slack.com/block-kit) instead of SlackNet.Bot and attachments. Using socket mode, you won't need to set up a web server, and blocks provide many more options for layout and interactivity. You can find an example of using the socket mode client in the [SocketModeExample](https://github.com/soxtoby/SlackNet/tree/master/SlackNet.SocketModeExample) project, and an example of using [block menus](https://github.com/soxtoby/SlackNet/blob/master/SlackNet.EventsExample/Startup.cs#L28) in the EventsExample project (the usage is the same as with socket mode).

Hope this helps. Let me know if you have any other questions.
