### ISSUE TITLE
Incorrect deserialization of the AppUninstalled event payload

### ISSUE THREAD

**Issue by LipatovAlexander** [soxtoby/SlackNet#113]
![image](https://user-images.githubusercontent.com/77479370/182271087-3c2595ac-68f3-47bf-91ac-78cb285350b8.png)
In the second screenshot, what was actually sent:
![image](https://user-images.githubusercontent.com/77479370/182271215-e7ad19f6-11c1-4982-ab62-702063fa7964.png)

**Comment by gingertez** [comment]
Me too!

I am building my first Slack App using SlackNet and today I tried to implement the `app_uninstalled` functionality.

I am facing the exact same issue. I've subscribed to the `app_uninstalled` event, my handler is registered, but the `slackEvent` looks like the OP's.

**Comment by gingertez** [comment]
I've hacked a workaround together... by creating a generic handler that implements `IHandler`. The `Handle` method for that gets called for everything not already handled (I think) and the parameter is the complete event wrapper.

See screenshots - first is my handler in action... second is my `Program.cs` (I'm on net 6.0 so it's there rather in `Startup.cs`)

![image](https://user-images.githubusercontent.com/470013/182453707-7b38693d-8396-4032-a9af-160923ac66fc.png)
![image](https://user-images.githubusercontent.com/470013/182453785-e73a912e-5cbb-4f60-a744-0f68f92ef7bd.png)

**Comment by soxtoby** [comment]
Thanks for raising this @LipatovAlexander,

Look like I made a mistake by including those properties on `AppUninstalled` when they're not part of the actual event. @gingertez has the right idea here - in order to access the metadata around the event, you'll need to implement `IEventHandler` and check the type of the event.

FWIW you can reliably check the type of the `Event` property, e.g.
```c#
public async Task Handle(EventCallback eventCallback) {
    if (eventCallback.Event is AppUninstalled) {
        // Handle uninstall
    }
}
```

Registering an `IEventHandler<T>` is just a convenience method to [wrap your handler with this type check](https://github.com/soxtoby/SlackNet/blob/f08c27c14c6fb78ff45d1465d3ca85d8039ad2a2/SlackNet/Handlers/TypedEventHandler.cs#L13), so you won't be missing out on any extra behaviour.

Hope that helps.

**Comment by gingertez** [comment]
@soxtoby it would be really helpful if you could mention somewhere in the AspNetCore part of the readme about the `IEventHandler<T>`  being a convenience method and that if we really want to get at the whole message, not just the `Event` properties, we should use `IEventHandler`.

Or... you could add a property to the base `Event` class which holds the wrapper properties so they're available on the event parameter in all the handlers?
