### ISSUE TITLE
SlackNet.EventsExample Documentation and Restructure Discussion

### ISSUE THREAD

**Issue by ClubSpeedJustinG** [soxtoby/SlackNet#119]
Hello @soxtoby, 

Just following up on this [PR](https://github.com/soxtoby/SlackNet/pull/118#issuecomment-1239173102).

**Discussion Topic 1**
The SlackNet.EventsExample example project contains examples for Event Subscriptions, Slash Commands, Interactivity, and Workflow Steps. From the perspective of a C# newbie developer that isn't familiar with the Slack API, it's a lot to take in. Should we create four separate example projects that showcase the Event Subscriptions, Slash Commands, Interactivity, and Workflow Steps? Each readme.md file could clearly elaborate on how/where to get the keys needed and where to set the RequestURLs. These readme.md files could also contain gifs of each one working. This would quickly allow the reader to know if that's what they are looking for.

Alternatively, if you think that the SlackNet.EventsExample should stay as one project, then would you be open to changing [this](https://github.com/soxtoby/SlackNet/blob/30dfb1c64d28f20e3d8bac921544fcab99c34203/SlackNet.EventsExample/readme.md) file? Specifically, could we create four sections (Event Subscriptions, Slash Commands, Interactivity, and Workflow Steps) that elaborates on how/where to get the keys needed and where to set the RequestURLs? 

**Discussion Topic 2**
The SlackNet.EventsExample project currently uses .NET 2.1, seen [here](https://github.com/soxtoby/SlackNet/blob/30dfb1c64d28f20e3d8bac921544fcab99c34203/SlackNet.EventsExample/SlackNet.EventsExample.csproj#L4). Would you be open to updating the SlackNet.EventsExample project to .NET 6?  

**Discussion Topic 3**
It sucks that the applications have to be public in order for the SlackNet.EventsExample projects to work. That alone is probably a reason to use WebSockets. Anyways, the readme.md file, seen [here](https://github.com/soxtoby/SlackNet/blob/30dfb1c64d28f20e3d8bac921544fcab99c34203/SlackNet.EventsExample/readme.md) mentions ngrok. A newbie might not know how to set this up. Could you provide more details or a link to an article that can help? Azure, AWS, and GCP are options too!

**Comment by soxtoby** [comment]
Thanks for the feedback, @ClubSpeedJustinG. It's made me take a step back to think about the documentation and examples more holistically. Sorry about this overly large response - It's mostly just me trying to make my thought process clear to myself.

## General thoughts

Currently, my motivations regarding documentation (including example projects and XML docs) are:
- Getting developers up and running with the Slack API quickly.
- Making it easy to use the API provided by Slack.
- Minimise maintenance and support, since I have limited time to work on this.

This has led me to the following strategy:
- Lean on Slack's documentation, since it covers their entire API and is kept up-to-date. Most of SlackNet's API mirrors Slack's own API, with links directly Slack's documentation.
- Provide instructions for getting started, with minimal unnecessary steps to avoid confusion.
- Provide example code that covers the different high-level APIs, to provide more context to the "getting started" instructions, and to point people in the right direction for finding undocumented APIs.

I think this has mostly worked out well, but due to the way the project has evolved over time as Slack has changed their API, the main readme and examples have ended up being focused on older, less easy to use, ways of doing things. In particular, until recently the readme promoted the `SlackNet.Bot` package fairly heavily, even though Slack deprecated the API it used quite a while ago.

`SlackNet.EventsExample` has ended up being the primary example project, since it covers both event-handling and message posting in a range of scenarios. When I created it, setting up a public web site was the only way to receive events from Slack, which is why it's called `EventsExample` and not `AspNetCoreExample`. With Slack's new socket mode feature, setting up a public web site is no longer a requirement, and getting an example project running should be much easier.

## Proposed changes

Based on the reasoning above and your feedback, I think the way to go is:
- Move all the example projects into an `Examples` folder, with its own readme that outlines what the different projects are for.
- Make the primary example project use socket mode, with appropriate instructions for getting it running. This will be much easier to get running than a public web site.
  - Make the different examples in the project (interactive messages, dialogs, workflow etc.) more explicit, both in the code and the readme.
  - Remove the legacy examples. These may have made sense during a transition period, but that time has long passed.
- Create an `AspNetCoreExample` project that focuses on ASP.NET Core integration, rather than general event handling.

## Feedback
Those are my high-level thoughts, but to address your points more explicitly:
- **Separate example projects for different examples**: My biggest concern with this is the effort required to maintain several similar projects with similar readmes, but I also think it would be trading the difficulty of finding the code you're interested in with the difficulty of finding the right project to look at. I think making the areas more explicit within the one example project will be easier to maintain, and overall easier to follow.
- **Clearly elaborating on how/where to get the keys needed (etc.)**: I agree that the example readme should be more like step-by-step instructions you can follow to get things working. I want to avoid being too specific about Slack's interface though (especially with images), in case they change something on their end and the instructions become misleading. There's also only so much guidance I can provide for something like workflows, which I'm not really familiar with and are quite involved.
- **GIFs of the examples**: Sounds like a lot of work to maintain, although screenshots of some of the examples might be worthwhile just to give you an idea of what to expect.
- **Sections in the readme for the different examples**: Totally agree with this. I'll try to differentiate them in the code more clearly as well.
- **.NET 6 for the ASP.NET example**: .NET 6 is still fairly new, so I'm a little wary about using it in examples. It makes sense for new projects, but makes it more difficult for anyone trying to integrate SlackNet into existing projects on older versions of .NET. That said, .NET 7 is just around the corner, and if the ASP.NET example is focused on the integration, rather than the event handling, then it's probably fine.
- **More details about using ngrok, and/or other hosting options**: Socket mode pretty much replaces the need for ngrok now, so I'll probably just take that part out. Since ASP.NET apps need to be public for Slack to talk to them, suggesting a few hosting services seems reasonable. I'll link to your blog post as an example of using AWS, but practically I can't go into detail about the other options. If the main example project is based on socket mode, hopefully there'll be less of a need for newbies to work out the hosting side of things.


I'll start on these changes soon, and push them up for further feedback. Rearranging the example projects will probably be quicker than writing this 😅 so I'll hopefully have something up within a week.

**Comment by mblack-montag** [comment]
I think it's important to point out this is an open source project based on an existing Open Api, the Slack API.  Most Git repositories, like this one, will provide enough documentation, test projects, and sample projects to get you going.  There are too many tools, technologies, architectures, and approaches to cover.

Besides, Slack has so much functionality that as a developer you need to figure out what you want to do.  You should understand the Slack best practices, the do's and don'ts, the limits, security, etc.  As a new developer, I recommend going to the Slack API site and reading everything there first.  Once you've figured out what kind of Slack app you want to build, try building it from scratch.  Then build the solution using SlackNet.  If you're having issues, you can then post the issue here and the code you're using so you can get help.

Here are some Slack links which should be helpful:

**Basic App Setup:** https://api.slack.com/authentication/basics
**Guided tutorials:** https://api.slack.com/tutorials
**Start Your Journey:** https://api.slack.com/start

Hope this helps and good luck!

**Comment by soxtoby** [comment]
I've pushed up a first pass of the re-worked examples as the [new-examples branch](https://github.com/soxtoby/SlackNet/tree/new-examples). I haven't had time to test anything yet, so I can't guarantee that the examples work, and the steps in the readmes aren't quite complete, but I think overall it's much clearer than what I had previously.

**Comment by ClubSpeedJustinG** [comment]
@soxtoby,

I so appreciate the amount of thought in your response. It's evident that you have spent time thinking about this. 

Regarding, 
```
Currently, my motivations regarding documentation (including example projects and XML docs) are:

Getting developers up and running with the Slack API quickly.
Making it easy to use the API provided by Slack.
Minimise maintenance and support, since I have limited time to work on this.
```

I agree with all of these points. Nice👍

As a developer looking at this repository for the first time, I would like to quickly know some of the features. 

Currently, the main [readme.md](https://github.com/soxtoby/SlackNet/blob/master/readme.md), seen in the screenshot below, talks a lot about how to set things up.
![image](https://user-images.githubusercontent.com/30958546/190951501-4ddc427c-4667-4397-a0d7-aa707332bbf5.png)


I don't know what this repository can do until digging a little deeper into the examples. I think the main [readme.md](https://github.com/soxtoby/SlackNet/blob/master/readme.md) would be an awesome opportunity to showcase some of the things that this repository can do! 

I'm very curious about how most people use this repository.

For instance, if 90% of the people that use this repository are just trying to send messages to Slack Channels, then an example like this could be beneficial in the main [readme.md](https://github.com/soxtoby/SlackNet/blob/master/readme.md).
```
await _slack.Chat.PostMessage(new SlackNet.WebApi.Message() { Text = "HelloWorld", Channel = "#tennis" }, null);
```

Or if 90% of the people that use this repository are looking for a way to type a message into a Slack Channel and get a response back, then the ping pong example could be showcased. I also agree that you should push socket mode and shy away from ```SlackNet.Bot```.

```
if (slackEvent.Text.Contains("ping")) {
    var user = await _slack.Users.Info(slackEvent.User).ConfigureAwait(false);
    var channel = await _slack.Conversations.Info(slackEvent.Channel).ConfigureAwait(false);
    await _slack.Chat.PostMessage(new Message {
        Text = "pong",
            Channel = slackEvent.Channel
    }).ConfigureAwait(false);
}
 ```

Regarding,
```
Based on the reasoning above and your feedback, I think the way to go is:

Move all the example projects into an Examples folder, with its own readme that outlines what the different projects are for.
Make the primary example project use socket mode, with appropriate instructions for getting it running. This will be much easier to get running than a public web site.
Make the different examples in the project (interactive messages, dialogs, workflow etc.) more explicit, both in the code and the readme.
Remove the legacy examples. These may have made sense during a transition period, but that time has long passed.
Create an AspNetCoreExample project that focuses on ASP.NET Core integration, rather than general event handling.
```
Love it
Love it 
Love it 
Love it
Love it

Regarding Feedback from Bullet 2,

```
Clearly elaborating on how/where to get the keys needed (etc.): I agree that the example readme should be more like step-by-step instructions you can follow to get things working. I want to avoid being too specific about Slack's interface though (especially with images), in case they change something on their end and the instructions become misleading. There's also only so much guidance I can provide for something like workflows, which I'm not really familiar with and are quite involved.
```

Yeah. I'd imagine that Slack's UI team gets bored and ends up changing the UI often 😂. It's always annoying for the developer to find where all of this is at, and it eats a lot of time. When hundreds of people are using this repository, that adds up to a lot of time and frustration. Understandable that you don't want to keep you updating this though.

Regarding Feedback from Bullet 3
```,
GIFs of the examples: Sounds like a lot of work to maintain, although screenshots of some of the examples might be worthwhile just to give you an idea of what to expect.
```
Personally, I think pictures would be awesome!! 


Regarding Feedback from Bullet 5,

```
.NET 6 for the ASP.NET example: .NET 6 is still fairly new, so I'm a little wary about using it in examples. It makes sense for new projects, but makes it more difficult for anyone trying to integrate SlackNet into existing projects on older versions of .NET. That said, .NET 7 is just around the corner, and if the ASP.NET example is focused on the integration, rather than the event handling, then it's probably fine.
```

I think .NET 6 is going to be supported for awhile, seen [here](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). I could be mistaken though. I think 2.1 is old 😛, but it's not really a big deal.

**Comment by ClubSpeedJustinG** [comment]
@mblack-montag ,

Regarding
```
Besides, Slack has so much functionality that as a developer you need to figure out what you want to do. You should understand the Slack best practices, the do's and don'ts, the limits, security, etc. As a new developer, I recommend going to the Slack API site and reading everything there first. Once you've figured out what kind of Slack app you want to build, try building it from scratch. Then build the solution using SlackNet. If you're having issues, you can then post the issue here and the code you're using so you can get help.
```

Agreed that the developer should look at the actual Slack API and become familiar with it before looking into C# repositories like this one. In practice developers aren't always that patient, surprisingly. They often want nearly instant gratification. I blame tiktok for our new limited attention spans.

**Comment by NotFazed** [comment]
Agree some additional usage examples as set out by the OP would be useful.

I'm really struggling to send a file into a channel.  My use case isn't in relation to a bot conversation with a user.  I just want to post a file into a channel with no interaction with an end user.

Does anyone have a code snippet that could help please.

**Comment by soxtoby** [comment]
I've "finished" updating the examples and readmes and merged everything into master. Thanks for all the feedback so far; it's been very helpful in trying to figure out what to include.

I'm going to close this issue and move on to other changes, but I'll still be thinking about how to improve the documentation in the future, so suggestions are still welcome! I do like the idea of including a picture or two in the main readme (I think you're spot on about GitHub repos looking much nicer with them, @ClubSpeedJustinG) - I just need to think of something that works.

**Comment by soxtoby** [comment]
@NotFazed Slack has documentation for [Uploading files to Slack](https://api.slack.com/messaging/files/uploading) and [Adding remote files to Slack](https://api.slack.com/messaging/files/remote) that I'd recommend.

Specifically for SlackNet, you'll probably want to use `api.Files.Upload()` (there's several overloads depending on whether you've got text, bytes, or a stream), or if the file is already hosted publicly, then `api.RemoteFiles.Add()` and then `api.RemoteFiles.ShareByExternalId()` or `api.RemoteFiles.ShareByFileId()`.

If you run into any trouble with these, please don't hesitate to open a new issue with the specifics.

**Comment by Justbeingjustin** [comment]
@NotFazed ,

I wrote an article that can assist with your issue. It can be found [here](https://medium.com/@justinshawngerber/send-a-file-to-a-slack-channel-using-c-3d036248c675). Hopefully someone finds the article helpful.
