### ISSUE TITLE
UWP samples

### ISSUE THREAD

**Issue by mediaexplorer74** [soxtoby/SlackNet#129]
Hi, Simon aka soxtoby! 
Nice/great project. Good luck! I remember sweet days when Slack does running at Windows Phones ) Nastalgie )) Please tell me, where to get some UWP samples for your great Slack.net lib? I dream on Lumia 950 at my hands with your Slack app, in 2023 )) Hehe! 

Best regards,
mediaexplorer74

**Comment by soxtoby** [comment]
Thanks for the question, @mediaexplorer74. I don't have any experience with UWP so unfortunately I can't provide a specific sample. Using SlackNet with UWP should be much the same as the [existing examples](https://github.com/soxtoby/SlackNet/tree/master/Examples) though, except that the configuration code would go somewhere else.

If you're using a dependency injection container (which is what I'd recommend), then SlackNet is configured wherever the container is configured, using the `AddSlackNet` extension method, and then you can resolve the socket mode client as in the examples to receive events from Slack, or similarly resolve the API client to talk to Slack.

Otherwise, you can configure SlackNet [without a container](https://github.com/soxtoby/SlackNet/tree/master/Examples/NoContainerExample), keep the service builder in a static field, and get the required services from there.

Just to be sure, SlackNet only provides access to Slack's events and API methods, so you'll need to create your own UI.

Hope this helps.

**Comment by mediaexplorer74** [comment]
> Thanks for the question, @mediaexplorer74. I don't have any experience with UWP so unfortunately I can't provide a specific sample. Using SlackNet with UWP should be much the same as the [existing examples](https://github.com/soxtoby/SlackNet/tree/master/Examples) though, except that the configuration code would go somewhere else.
> 
> If you're using a dependency injection container (which is what I'd recommend), then SlackNet is configured wherever the container is configured, using the `AddSlackNet` extension method, and then you can resolve the socket mode client as in the examples to receive events from Slack, or similarly resolve the API client to talk to Slack.
> 
> Otherwise, you can configure SlackNet [without a container](https://github.com/soxtoby/SlackNet/tree/master/Examples/NoContainerExample), keep the service builder in a static field, and get the required services from there.
> 
> Just to be sure, SlackNet only provides access to Slack's events and API methods, so you'll need to create your own UI.
> 
> Hope this helps.

Thank you for your advice. Well, DI is clever thing. I 'll RnD your great code

Best wishes,
mediaexplorer
