### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by the-unforgiven666** [soxtoby/SlackNet#138]
Hi, thanks for this excellent package.
I started playing around with Block Kit Elements and so far everything works nicely except for DatePicker. I couldn't finally figure out the issue ("internal error"), but while debugging with https://api.slack.com/methods/views.publish/test, I found if I uncomment "FocusOnLoad" property from datepicker class it works fine.

Its reproducable using above test-link with this json (and adding/removing _focus_on_load_ in below json) 

```
{
    "type": "home",
    "blocks": [
    {
        "elements": [
        {
            "placeholder": {
                "type": "plain_text",
                "text": "yo"
            },
            "initial_date": "1990-04-28",
            "focus_on_load": true,
            "action_id": "someid",
            "type": "datepicker"
        }],
        "type": "actions",
    }]
}
```

Any clue?

**Comment by soxtoby** [comment]
Hi @the-unforgiven666,

As far as I can tell, it should work - there's nothing in the docs that would indicate otherwise, and I tried a few other element types and they work just fine with `focus_on_load`. Given that it's an internal error, rather than a validation error, I suspect the issue is on Slack's end. I think you'll need to contact them to resolve the error.

In the meantime, it looks like the view is still updated in the Slack app, so you may be able to get by just by catching and ignoring this specific error.

**Comment by the-unforgiven666** [comment]
Hi @soxtoby,
thanks for your quick response.
I also found that the docs to state focus_on_load is OK for the date picker. I'll try to reach someone at Slack - it may help that we are paying customer ;-)

**Comment by soxtoby** [comment]
As of [v0.10.19](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.19), `focus_on_load` is no longer serialized for date pickers when the value is false, so it should be easy to avoid Slack's internal error now.
