### ISSUE TITLE
Non conventional way to name async methods

### ISSUE THREAD

**Issue by doxakis** [soxtoby/SlackNet#14]
Hi,

I was reading your readme and I found out in the example you are using a non conventional way to name async methods.

According to the Microsoft documentation, it suggests :
> You should add "Async" as the suffix of every async method name you write.
> https://docs.microsoft.com/en-us/dotnet/csharp/async#important-info-and-advice

Thanks!

**Comment by soxtoby** [comment]
Hi, thanks for the comment.

This is a deliberate design decision on my part: since the entire API is asynchronous, there's no need to differentiate between synchronous and asynchronous methods. [This page in the NServiceBus documentation](https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix) mirrors my thinking almost exactly, and explains it much better than I ever could.

Hope this helps.
