### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by gilmatok** [soxtoby/SlackNet#148]
Slack's Bolt has support for global middleware that can be run for all incoming requests. This way you can authenticate users with your app.

In addition, you can also enrich requests with "context": https://slack.dev/bolt-python/api-docs/slack_bolt/context/index.html.

Is there similar support in SlackNet?

**Comment by soxtoby** [comment]
Thanks for the question, @gilmatok. There's currently no generic middleware support, but you _can_ wrap all the request handlers with your own implementation to achieve a similar result using the `.Replace*()` methods available at configuration time. The replace methods take in a factory callback which is provided with the Slack request context. The request context can also be accessed via `SlackRequestContext.Current`.

Your custom handler should take in another handler to pass to, e.g.
```c#
class CustomHandler : IAsyncBlockActionHandler
{
    private readonly IAsyncBlockActionHandler _innerHandler;
    private readonly SlackRequestContext _context;

    public CustomHandler(IAsyncBlockActionHandler innerHandler, SlackRequestContext context)
    {
        _innerHandler = innerHandler;
        _context = context;
    }

    public async Task Handle(BlockActionRequest request, Responder respond)
    {
        // Borrowed from the Bolt context example, but you can do whatever you want here
        _context["tz_offset"] = request.User.TzOffset;

        // Pass control to the regular handler
        await _innerHandler.Handle(request, respond);
    }
}
```

The inner handler will need to be constructed manually to be passed into your custom handler, but fortunately the default handlers are all very simple, starting with either `Composite*` or `Switching*`, and taking in a collection of handlers. Using your custom handler will then look something like this:
```c#
slackConfiguration
    .ReplaceBlockActionHandling(ctx =>
        new CustomHandler(
            new CompositeBlockActionHandler(ctx.BlockActionHandlers), // The default handler
            ctx))
```

Hopefully this provides what you need for now. I like the idea of adding a simpler, more generic middleware feature at some point, but it might be tricky to get the typing right, since Slack sends requests in quite a number of formats (looks like Bolt supports middleware for its two dynamically typed languages, but not for Java, which might be telling).

**Comment by gilmatok** [comment]
@soxtoby Thanks for the quick reply. I looked at the custom handler option when I tried to dig into the code, however it seems a bit cumbersome for my needs; a generic one would probably be much better if possible, in the future.

Closing this for now.
