### ISSUE TITLE
Do I need both API and socket/app level token?

### ISSUE THREAD

**Issue by Regenhardt** [soxtoby/SlackNet#171]
In the examples, the socket mode seems to be used for receiving events to the event handler, but the response is always sent via SlackApiClient, which seems to need an API token (I always get not_authed, without it).

Can I just use the socket connection to reply (or send messages otherwise), without the additional API token?

**Comment by soxtoby** [comment]
Thanks for the question, @Regenhardt. Socket mode is a way to use Slack's [Events API](https://api.slack.com/apis/connections/events-api) without needing to host public HTTP endpoints, so it can only _receive_ events and interaction requests, not initiate. It's possible to respond to slash commands with a message, but otherwise you'll need to use the API client with a bot or user token to post messages.
