### ISSUE TITLE
Trigger ID missing from ViewSubmission

### ISSUE THREAD

**Issue by hughesmk** [soxtoby/SlackNet#180]
We have been working on creation some more complex models that would need to push new modals on to the stack.  Unfortunately that requires the trigger id which does not seem to be exposed by Slacknet.interaction.viewsubmission although it is in the raw json payload.

I do see the triggerid in other similar classes so I plan to test just adding it to viewsubmission to see if that gives the needed information.   In parallel I figured I cannot be the first person to have gotten here and would ask if perhaps I am going about things the wrong way.

**Comment by hughesmk** [comment]
Adding
public string TriggerId {get; set; } 
to ViewSubmission.cs does solve the problem of not having access to the TriggerID for pushing updates to the modals.

**Comment by soxtoby** [comment]
I'd recommend responding to the view submission with a `PushViewResponse` rather than using the API.

If not pushing another view on top, view submissions always result in either the modal being updated, showing errors, or being closed, and I don't think it would make sense do any of these _and_ push a new view. Additionally, Slack's modal documentation for [adding a new view via API](https://api.slack.com/surfaces/modals#add_api) indicates that it should only be triggered by an interactive component inside the modal.

Hope that helps.
