### ISSUE TITLE
Long running Azure Function handlers being retried by Slack

### ISSUE THREAD

**Issue by j5alive** [soxtoby/SlackNet#188]
With the recent changes / addition of the `SlackNet.AzureFunctions` project, when you have an event handler for a long running (greater than 3 seconds), Slack will now retry the endpoint as it doesn't return quick enough.

It seems related to the comment and code in the `SlackFunctionResult`, see https://github.com/soxtoby/SlackNet/blob/4ed543f3425d2cb0798abb80c4418cc45a2c7876/SlackNet.AzureFunctions/SlackFunctionResult.cs#L16

If I remove the `await` from `await callback();` on line 19 then I no longer have the issue (as the handlers are now running in the background after the request has ended).

I also looked at changing the stored `Func<Task>` in `RequestCompletedCallbacks` to store a list of `Action`s which does work, but I don't know what the flow-on from this sort of change would be, much larger I guess if there are callbacks needing to be awaited.

Is the removal of the `await` in `SlackFunctionResult` something that could be done, or is there a better approach to this issue?

**Comment by j5alive** [comment]
I've also worked around the issue for now, in my handler I just push everything to a background Task.
```
public Task Handle( MessageEvent slackEvent )
{
  Task.Run( ( ) => Process( slackEvent ) );
  return Task.CompletedTask;
}
```

**Comment by soxtoby** [comment]
Thanks for the question, @j5alive. Since [Azure Functions can shut down after responding to the request](https://learn.microsoft.com/en-us/azure/azure-functions/performance-reliability#make-sure-background-tasks-complete), I'd recommend queuing any long-running work using an Azure Queue, and picking it up with another function triggered by that queue.

Hope that helps.
