### ISSUE TITLE
Serialized message payload

### ISSUE THREAD

**Issue by hughesmk** [soxtoby/SlackNet#208]
So I have a perhaps unusual request that I hope you can guide me on.   I have bots running in multiple grids, I would like to be able to store the serialized message in a database table so that I can queue it to be sent by a bot in a different grid.    While i can easily create the block kit payload manually i do no see a way to grab it from the slackbot.Net api nor an easy way to send that block kit message.  I am hoping that this two items are trivial and I am just missing the forest through the trees and you can just point me the right way.

**Comment by soxtoby** [comment]
Hi @hughesmk. It's not entirely clear to me where the messages are coming from that you're serializing, or which SlackNet API you're sending them with, so I'll try to cover all the bases here.

**Using event handlers and `ISlackApiClient.Chat.PostMessage`:**
Your event handler will receive some kind of `MessageEvent`. These contain a lot of metadata that can't be directly translated to the `Message` type that `PostMessage` takes in, but you should be able to copy across most of the `Message` properties directly. I'd probably recommend converting the `MessageEvent` to a `Message` before serializing, unless you need some of that extra metadata after deserializing on the other side.

**Using SlackNet.Bot API:**
This is going to be a bit trickier, since the bot API was geared towards ease-of-use rather than flexibility. The messages that the bot exposes to handlers are `SlackMessage`s, which contain a reference to the bot, so they're definitely not serializable. The `BotMessage`s that are used for sending messages similarly contain several types that probably won't serialize. In this case you'd need copy the relevant properties over to your own class designed for serialization, then copy them back to a `BotMessage` for sending to Slack.

In both cases, if you're looking for the block kit blocks specifically, they'll be in the `Blocks` property, which contains an `IList<Block>`, which should serialize just fine.

Hope this helps.
