### ISSUE TITLE
Support for slash commands

### ISSUE THREAD

**Issue by LunicLynx** [soxtoby/SlackNet#26]
I'm wondering is there support for slash commands?

I guess it would be possible to todo this via message events. But then the slack ui would not show the slash command info.

If there isn't support, how can i serialize a MassageResponse manually?

**Comment by x10an14** [comment]
If I'm guessing correctly, when you write "slash commands", you're referring to Slack's "Ephemeral messages."

There is some support for them, but I haven't quite gotten far enough in my own project using this framework to speak from any position of experience.

https://github.com/soxtoby/SlackNet/search?l=C%23&q=ephemeral

**Comment by LunicLynx** [comment]
Not exactly slash commands do have their own endpoints and behaviors. Like response urls etc.

**Comment by soxtoby** [comment]
There's no slash command support at the moment. Since each command can have its own URL, I figured it would be easier to just set up a regular controller action and take Slack's parameters in as the action's parameters.

`MessageResponse` isn't a valid response itself since it wraps a message, rather than extending it. So you'll need to wrap it in `MessageUpdateResponse` and serialize that with the Json.NET settings provided by the `SlackJsonSettings` service.

The end result would be something like this:
```c#
[ApiController]
public class SlashCommandsController
{
    private readonly SlackJsonSettings _slackJson;
    public SlashCommandsController(SlackJsonSettings slackJson) => _slackJson = slackJson;

    [Route("Echo")]
    public JsonResult Echo([FromForm] string text)
    {
        var response = new MessageResponse { ResponseType = ResponseType.InChannel, Message = new Message { Text = text } };
        return new JsonResult(new MessageUpdateResponse(response), _slackJson.SerializerSettings);
    }
}
```

...which to be honest, now that I look at it, is not as straightforward as I thought it would be.

I'll look into adding a way of handling slash commands similar to the way other events/actions are handled.

**Comment by LunicLynx** [comment]
> I'll look into adding a way of handling slash commands similar to the way other events/actions are handled.

That would be great. Let me know if i can help with that.

Currently i did something similar to what you suggested. One controller i use for all the commands under `http://<host>/slack/commands` then switching to the right command handler and processing the parameters.

I did not see how i could utilize the response url with what is currently available. I'm also wondering if there is a way to update the message that can be returned as part of the response to a slash command. I don't see ho to get the Timestamp currently.

**Comment by LunicLynx** [comment]
Thanks, this looks promising.
