### ISSUE TITLE
Answer to channel later

### ISSUE THREAD

**Issue by felipe-sbatista** [soxtoby/SlackNet#49]
Hey Simon, thank you for your code!

Could you help me?
I got a message from slack channel user and i send it to a queue ( Kafka or rabbit) to process it in another service. When the service finishes, i got a response to send to the slack channel. But I dont know how to send it to the channel back because i dont have the IMessage object anymore to use ReplyWith for example.

PS: I've tried to instantiate in a simple way, but it did not work, like: 
`var bot = new SlackBot("token");
bot.Send(New BotMessage{Text = "test"};`

Thank you!

**Comment by soxtoby** [comment]
Hi Felipe,

For this scenario, you'll want to use `SlackApiClient` directly instead of going through `SlackBot`. The rough equivalent to `IMessage.ReplyWith` is:

```c#
var client = new SlackApiClient("bot token");
await client.Chat.PostMessage(new Message {
    Channel = originalMessage.Hub.Id,
    ThreadTs = originalMessage.ThreadTs,
    Text = "test",
    //  ...etc.
});
```

The key parts are the `Hub.Id` and `ThreadTs` from the original message being replied to - you'll need to hold on to these. They're both just strings, so it should be straightforward to store them somewhere or pass them along through the queue.

Hope this helps.

**Comment by felipe-sbatista** [comment]
It helps! Thank you so much!
