### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by hughesmk** [soxtoby/SlackNet#54]
I need to be able to connect to slack via an authenticated proxy and thus far have not figured out how to pass the information through so that the websocket connection can be made.  I am hoping that you might be able to point me the right direction.

**Comment by soxtoby** [comment]
I've never needed to connect through a proxy so I can't give you specifics, but you'll need to inject your own implementations of `IHttp` and `IWebSocketFactory` into `SlackBot`. Instead of using the simple constructor that just takes an API token, you'll need to provide all of its dependencies, like this:

```cs
var jsonSettings = Default.JsonSettings(Default.SlackTypeResolver(Default.AssembliesContainingSlackTypes));
var client = new SlackApiClient(new ProxySupportingHttp(jsonSettings), Default.UrlBuilder(jsonSettings), "<your token>");
var bot = new SlackBot(new SlackRtmClient(client, new ProxySupportingWebSocketFactory(), jsonSettings), client);
```

`ProxySupportingHttp` can probably be a copy of [Http](https://github.com/soxtoby/SlackNet/blob/master/SlackNet/Http.cs) with its own `HttpClient` that's been configured with the proxy.
`ProxySupportingWebSocketFactory` would be a copy of [WebSocketFactory](https://github.com/soxtoby/SlackNet/blob/master/SlackNet/WebSocketFactory.cs) that configures the `WebSocket`s with the proxy.

I could probably tweak some of the defaults to make this easier, but in the meantime I hope this helps.

**Comment by hughesmk** [comment]
Thank you very much this was enough of a push in the right direction, I was able to get things working.

**Comment by soxtoby** [comment]
I made some changes to the `Defaults` class in v0.7.3, so the above code becomes a bit simpler:
```c#
var httpMessageHandler = new HttpClientHandler(); // Configure this with proxy settings
var client = new SlackApiClient(Default.Http(httpClient: new HttpClient(httpMessageHandler)), Default.UrlBuilder(), "<your token>");
var bot = new SlackBot(new SlackRtmClient(client, new ProxySupportingWebSocketFactory(), Default.JsonSettings()), client);
```

**Comment by nztomas** [comment]
Please could you post complete example with proxy, I really struggle with it. Mainly with ProxySupportingWebSocketFactory...

Would be to hard to create a constructor where I can pass the proxy url as second parameter and all the hard work would happen behind the scene? Thanks...
