### ISSUE TITLE
Support for responding to threaded app mentions

### ISSUE THREAD

**Issue by Julian-Robinson** [soxtoby/SlackNet#66]
Hi @soxtoby 

I've got a bot user I'm driving primarily off app mention events and it looks like there is some additional properties available when an app mention event is fired from a threaded response that are not available on the AppMention class - In particular the `thread_ts` property which any responses need if they are to be included in the same thread.

Examples below show the different event payloads - I've excluded the event wrapper and some other properties for brevity - happy to provide more info if needed. 

#### Regular mention:
```
 "event": {
        "client_msg_id": "a9ee5a2d-2035-474e-9ac7-887472933ebe",
        "type": "app_mention",
        "text": "<@U01D85NCC79> mention from conversation",
        "user": "U01........",
        "ts": "1604565265.015200",
        "blocks": [...],
        "event_ts": "1604565265.015200"
    },
```

#### Threaded mention
```
    "event": {
        "client_msg_id": "e38e7ef8-4b97-44b9-9d39-1e93a3f8c3a3",
        "type": "app_mention",
        "text": "<@U01D85NCC79> threaded mention",
        "user": "U01........",
        "ts": "1604565284.015600",
        "blocks": [...],
        "thread_ts": "1604565265.015200",
        "parent_user_id": "U01........",
        "event_ts": "1604565284.015600"
    },
```

Wondering what the best approach would be to get the `thread_ts` property off the threaded app mention events? Should they be added to the AppMention class here? The [docs](https://api.slack.com/events/app_mention) mention _"The app_mention event is not a message like the message.* event types. However, your app can treat its contents similarly."_ so there may be a handful of other properties in the same boat.  Happy to put a PR together if you want to go ahead with this approach. 

Otherwise is there an easy way to hook into the `ISlackTypeResolver` and provide some additional classes that could then be used in `RegisterEventHandler`? It looks like it's defined by some assembly scanning? I was half way through attempting to register a custom `ISlackTypeResolver`, passing in an additional assembly that contained a few additional types before I thought I'd just ask here :) 

Great first impressions of these packages so far though - Thanks!

**Comment by soxtoby** [comment]
Hi @Julian-Robinson 

You _can_ add assemblies to resolve types from by registering a new type resolver after `AddSlackNet` has been called with `services.AddSingleton(Default.SlackTypeResolver(Default.AssembliesContainingSlackTypes.Concat(<your assemblies here>).ToArray()));`, which would allow you to provide your own `AppMention` class.

I'd love to get these extra properties into SlackNet though, so a PR would be welcome. Or if you can provide example JSON with all the properties for completeness, then I'd be happy to add them myself since it won't take long. Just the top level like you've provided above would be fine; the contents of properties like `blocks` are pretty standard.

Cheers.
