### ISSUE TITLE
Should the api client contain a `ResetApiToken` method function?

### ISSUE THREAD

**Issue by misterjohannesson** [soxtoby/SlackNet#91]
Suggestion:
After the whole [token rotation](https://api.slack.com/authentication/rotation) enabled as default for new apps, the tokens used for the api client will have to be changed throughout the application lifetime. Simply saving the previous single token in the application configuration won't allow for most API calls to return a successful result.

![image](https://user-images.githubusercontent.com/17781340/135308708-de0fddaf-eb46-458e-929c-901e65a84b6c.png)

Currently, I have created a simple new client that uses the `SlackServiceBuilder` and returns a new instance of `ISlackApiClient`.

```csharp
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using Slack.Options;
using SlackNet;

namespace Slack.Clients
{
  public class SlackClient
  {
    private readonly SlackTokenCache slackTokenCache;
    private readonly SlackOptions options;

    public SlackClient(IOptions<SlackOptions> options, SlackTokenCache slackTokenService)
    {
      this.options = options.Value;
      this.slackTokenCache = slackTokenService;
    }

    public async Task<ISlackApiClient> GetApiClient(CancellationToken cancellationToken)
    {
      // Check if the token is in the cache, providing the method to retrieve it if not.
      var token = await slackTokenCache.GetToken(GetBotOAuthToken, cancellationToken);

      return new SlackServiceBuilder()
        .UseApiToken(token)
        .GetApiClient();
    }

    private async Task<string> GetBotOAuthToken(CancellationToken cancellationToken)
    {
      var refreshClient = new SlackServiceBuilder()
        .GetApiClient();

      var acessResponse = await refreshClient.OAuthV2.Access(
          clientId: this.options.ClientId,
          clientSecret: this.options.ClientSecret,
          grantType: "refresh_token",
          refreshToken: this.options.BotRefreshToken,
          redirectUrl: null,
          code: null,
          cancellationToken: cancellationToken
        );

      return acessResponse.AccessToken; // this token is by documentation the "Bot OAuth Token".
    }
  }
}
```

But I am thinking if perhaps the client itself should have a `ResetApiToken` and then the implementors can themselves handle fetching the new tokens.
I think usage would be something like this:

```csharp
var client = new SlackServiceBuilder()
        .UseApiToken("")
        .GetApiClient();
        
var oauthtoken = GetBotOAuthToken();

client.ResetApiToken(oauthtoken);

client.Auth.Test(); 
```

**Comment by soxtoby** [comment]
Definitely need something like this. My concerns with a method like `ResetApiToken` are that people would be too tempted to use it instead of `WithAccessToken`, leading to subtle bugs, and that you'd need to manage your own refresh scheduling, which seems like a pain.

Looking at [Slack's Bolt framework](https://slack.dev/bolt-js/concepts#authenticating-oauth), they automatically refresh tokens each request if there's less than 2 hours remaining on the token, and all you have to implement is a store for the token with get/set methods. This seems ideal to me, but I haven't wrapped my head around the app install/auth workflow enough to add something like this yet.

What I'm thinking in the meantime, is that `SlackApiClient` could get its token from something like this:
```c#
interface ISlackTokenProvider
{
    Task<string> GetToken(ISlackApiClient apiClient);
}
```
which would allow you to hook into requests transparently. I think this would set things up for built-in auto-refreshing, although the interface might need to change at some point to add more context.

Let me know your thoughts.
