### ISSUE TITLE
Inconsistent acknowledge response to Slack

### ISSUE THREAD

**Issue by raulcanales** [soxtoby/SlackNet#93]
Hi there,

Due to internal firewall, I'm forced to use my Slack application in Socket mode.

I have a very basic bot that is listening for events triggered when a message is sent to a public channel.

I noticed that even though it works, it does it inconsistently, some times it works, some times it doesn't. I've repeated exactly the same text intentionally with same randomized results. I even added a log entry in the event handler to just log a line upon receiving the event, before trying to do anything with the event itself, and sometimes it doesn't even hit that line.

I've contacted Slack support and they told me:

> We're seeing inconsistency with the acknowledgement to the event callbacks by your websocket connection (where it would send back the `envelope_id`).

I've been looking at the code where I suspect something may be happening ([link](https://github.com/soxtoby/SlackNet/blob/ce9024f0a3a08aa526acedf75f84553a49bc4f0c/SlackNet/SlackSocketModeClient.cs#L67)) and I can see that the exception is being ignored.

I was wondering if there's any way to get logging out of the box for every message received by Slack? Or perhaps don't swallow the exception and let it be picked up by the consumer? 

At the moment I'm blind as I cannot see what is happening under the hood.

Any ideas of what could be happening or how to troubleshoot further?

**Comment by soxtoby** [comment]
Hi @raulcanales, thanks for raising this.

First thing I'd try is to set the number of connections to 1 by passing an options object in as the second argument to `UseSocketMode`. I did see some inconsistent behaviour while developing multi-connection support, which I thought I had nailed down, but perhaps I missed something.

You mentioned exceptions being swallowed in the socket mode client; have you seen any exceptions while debugging, or is it just a (reasonable) hunch? Exceptions there could explain what you're seeing, so any information we can get on them would be helpful... which is obviously where logging would come in handy...

I _did_ start work on a logging implementation a while ago, which I don't mind getting back to, but it would be at least a week before I could get it to a releasable state. In the meantime, in order to debug this, you could override the web socket factory in order to wrap the web sockets with logging. The implementation would look something like this:

```csharp
class LoggingWebSocketFactory : IWebSocketFactory
{
    private readonly ILogger<LoggingWebSocket> _logger;
    public LoggingWebSocketFactory(ILogger<LoggingWebSocket> logger) => _logger = logger;
    public IWebSocket Create(string uri) => new LoggingWebSocket(new WebSocketWrapper(new WebSocket(uri, sslProtocols: SslProtocols.Tls12)), _logger);
}

class LoggingWebSocket : IWebSocket
{
    private readonly IWebSocket _inner;
    private readonly ILogger<LoggingWebSocket> _logger;

    public LoggingWebSocket(IWebSocket inner, ILogger<LoggingWebSocket> logger)
    {
        _inner = inner;
        _logger = logger;
    }

    public void Send(string message)
    {
        _logger.LogInformation(message);
        _inner.Send(message);
    }
    
    public IObservable<string> Messages => _inner.Messages.Do(m => _logger.LogInformation(m));

    // Delegate to inner web socket for everything else, adding logging as necessary
    public void Open() => _inner.Open();
    public WebSocketState State => _inner.State;
    public IObservable<Unit> Opened => _inner.Opened;
    public IObservable<Unit> Closed => _inner.Closed;
    public IObservable<Exception> Errors => _inner.Errors;
    public void Dispose() => _inner.Dispose();
}
```
The web socket factory can then be overridden in `ConfigureServices` with `.UseWebSocketFactory<LoggingWebSocketFactory>()` inside the `AddSlackNet` config. This wouldn't capture the exceptions which may be occurring, but it should provide a lot more visibility into what's being sent back and forth.

I'll try to look at the logging soon, but hopefully this helps in the shorter term.
